-- Event Tracker Database Schema
-- Version 0.1
--
-- This schema defines the durable storage structure for Event Tracker.
-- The physical exercise_type field is retained for compatibility, but it is
-- treated as event_name by the generalized capture and analysis layers.

CREATE TABLE IF NOT EXISTS events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    -- Stable ID generated by the capture device.
    -- Used to prevent duplicate imports from phone sync packages.
    source_event_id TEXT,
    
    -- When this record was created in the database.
    created_at TEXT NOT NULL,

    -- When the event actually occurred.
    -- For Version 0.1, this will default to the same value as created_at.
    occurred_at TEXT NOT NULL,

    -- Generic event category. Current generalized capture uses 'event';
    -- legacy structured records may use 'exercise'.
    event_type TEXT NOT NULL,

    -- Compatibility storage field used as the event name.
    exercise_type TEXT NOT NULL,

    -- Optional structured measurement.
    -- New general events may leave this null.
    amount REAL,

    -- Optional unit associated with amount.
    unit TEXT,

    -- Optional free-text note.
    note TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_events_source_event_id
ON events(source_event_id)
WHERE source_event_id IS NOT NULL;
